trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import include
from django.urls import reverse_lazy, path, re_path
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

import trapper.apps.media_classification.views.ai_classifications
from trapper.apps.media_classification.views import (
    api as classification_api_views,
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    ai_classifications as ai_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views,
)

app_name = "media_classification"

router = DefaultRouter(trailing_slash=False)

router.register(
    r"classificators",
    classification_api_views.ClassificatorViewSet,
    basename="api-classificator",
)

router.register(
    r"user-classifications",
    classification_api_views.UserClassificationViewSet,
    basename="api-user-classification",
)

router.register(
    r"classifications",
    classification_api_views.ClassificationViewSet,
    basename="api-classification",
)

router.register(
    r"ai-classifications",
    classification_api_views.AIClassificationViewSet,
    basename="api-ai-classification",
)

router.register(
    r"classifications_map",
    classification_api_views.ClassificationMapViewSet,
    basename="api-classification-map",
)

router.register(
    r"projects",
    classification_api_views.ClassificationProjectViewSet,
    basename="api-classification-project",
)

router.register(
    r"project/(?P<project_pk>\d+)/collections",
    classification_api_views.ClassificationProjectCollectionViewSet,
    basename="api-classification-project-collection",
)

router.register(
    r"sequences", classification_api_views.SequenceViewSet, basename="api-sequence"
)

router.register(
    r"collection/(?P<collection_pk>\d+)/resources/$",
    classification_api_views.ClassificationResourcesViewSet,
    basename="api-classification-resources",
)

urlpatterns = [
    re_path(r"^api/", include(router.urls)),
    re_path(
        r"^api/classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsView.as_view(),
        name="api-classification-results",
    ),
    re_path(
        r"^api/ai-classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.AIClassificationResultsView.as_view(),
        name="api-ai-classification-results",
    ),
    re_path(
        r"^api/classifications/results/agg/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsAggView.as_view(),
        name="api-classification-results-agg",
    ),
    re_path(
        r"^api/classifications/import/",
        classification_api_views.ClassificationImport.as_view(),
        name="api-classification-import",
    ),
    re_path(
        r"^api/media/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationProjectMediaTableView.as_view(),
        name="api-media-export",
    ),
    re_path(
        r"^api/package/(?P<project_pk>\d+)/",
        classification_api_views.ResultsDataPackageAPIView.as_view(),
        name="api-package-export",
    ),
    path(
        "api/classify/ai/callback/<str:ai_provider_token>/",
        classification_api_views.classify_ai_callback,
        name="api-classify-ai-callback",
    ),
    path(
        "api/classify/ai/classification_extra/<str:ai_provider_token>/<str:classification_job_id>/<str:resource_name>/",
        classification_api_views.classify_ai_extra_resource,
        name="api-classify-ai-extra",
    ),
]

urlpatterns += [
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("media_classification:project_list")),
        name="project_index",
    ),
    # Project views
    re_path(r"project/list/$", projects_views.view_project_list, name="project_list"),
    re_path(
        r"project/detail/(?P<pk>\d+)/$",
        projects_views.view_project_detail,
        name="project_detail",
    ),
    re_path(
        r"project/create/$", projects_views.view_project_create, name="project_create"
    ),
    re_path(
        r"project/update/(?P<pk>\d+)/$",
        projects_views.view_project_update,
        name="project_update",
    ),
    re_path(
        r"project/delete/(?P<pk>\d+)/$",
        projects_views.view_project_delete,
        name="project_delete",
    ),
    re_path(
        r"^project/delete/$",
        projects_views.view_project_delete,
        name="project_delete_multiple",
    ),
    re_path(
        r"project/collection/add/$",
        projects_views.view_project_collection_add,
        name="project_collection_add",
    ),
    re_path(
        r"project/collection/delete/(?P<pk>\d+)/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete",
    ),
    re_path(
        r"^project/collection/delete/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete_multiple",
    ),
    re_path(
        r"^project/collection/blur/$",
        projects_views.view_project_collection_blur_humans,
        name="project_collection_blur_humans",
    ),
    # Classificator views
    re_path(
        r"classificator/list/$",
        classificators_views.view_classificator_list,
        name="classificator_list",
    ),
    re_path(
        r"classificator/detail/(?P<pk>\d+)/$",
        classificators_views.view_classificator_detail,
        name="classificator_detail",
    ),
    re_path(
        r"classificator/create/$",
        classificators_views.view_classificator_create,
        name="classificator_create",
    ),
    re_path(
        r"classificator/update/(?P<pk>\d+)/$",
        classificators_views.view_classificator_update,
        name="classificator_update",
    ),
    re_path(
        r"classificator/clone/(?P<pk>\d+)/$",
        classificators_views.view_classificator_clone,
        name="classificator_clone",
    ),
    re_path(
        r"^classificator/delete/(?P<pk>\d+)/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete",
    ),
    re_path(
        r"^classificator/delete/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete_multiple",
    ),
    # Sequence views
    re_path(
        r"sequence/create/$",
        sequences_views.view_sequence_change,
        name="sequence_create",
    ),
    re_path(
        r"sequence/update/$",
        sequences_views.view_sequence_change,
        name="sequence_update",
    ),
    re_path(
        r"sequence/change/$",
        sequences_views.view_sequence_change,
        name="sequence_change",
    ),
    re_path(
        r"sequence/delete/$",
        sequences_views.view_sequence_delete,
        name="sequence_delete",
    ),
    re_path(
        r"^sequence/build/$", sequences_views.view_sequence_build, name="sequence_build"
    ),
    # Classification views
    re_path(
        r"^classification/overview/$",
        classifications_views.view_classification_overview,
        name="classification_overview",
    ),
    re_path(
        r"^classification/list/(?P<pk>\d+)/$",
        classifications_views.view_classification_list,
        name="classification_list",
    ),
    re_path(
        r"classification/import/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/import/(?P<pk>\d+)/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/export/(?P<pk>\d+)/$",
        classifications_views.view_classification_export,
        name="classification_export",
    ),
    re_path(
        r"classification/publish/$",
        classifications_views.view_classification_publish,
        name="classification_publish",
    ),
    re_path(
        r"classification/feedback/(?P<pk>\d+)/$",
        classifications_views.view_classification_feedback,
        name="classification_feedback",
    ),
    re_path(
        r"classification/export-agg/(?P<pk>\d+)/$",
        classifications_views.view_classification_export_agg,
        name="classification_export_agg",
    ),
    re_path(
        r"classification/importattrs/(?P<pk>\d+)/$",
        classifications_views.view_classification_import_attrs,
        name="classification_importattrs",
    ),
    re_path(
        r"^classification/delete/(?P<pk>\d+)/$",
        classifications_views.view_classification_delete,
        name="classification_delete",
    ),
    re_path(
        r"^classification/delete/$",
        classifications_views.view_classification_delete,
        name="classification_delete_multiple",
    ),
    re_path(
        r"^classification/bulk-update/$",
        classifications_views.view_classification_bulk_update,
        name="classification_bulk_update",
    ),
    re_path(
        r"classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$",
        classifications_views.view_classify_collection,
        name="classify_collection",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify_user",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    path(
        "classify/<int:pk>/ai/<int:ai_provider_id>/",

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy, re_path
from django.views.decorators.cache import cache_control, cache_page, never_cache
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from trapper.apps.accounts.views import accounts as accounts_views
from umap import views as umap_views
from umap.decorators import (
    map_permissions_check,
    login_required_if_not_anonymous_allowed,
)
from umap.utils import decorated_patterns

admin.autodiscover()


swagger_schema_view = get_schema_view(
    openapi.Info(
        title="TRAPPER API",
        default_version="v1",
        description="",
        terms_of_service="terms of service",
        contact=openapi.Contact(email="contact@os-conservation.org"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=[permissions.IsAuthenticated],
)


urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    re_path(
        r"^account/inactive/$",
        RedirectView.as_view(url=reverse_lazy("trapper_index")),
        name="account_inactive",
    ),
    # Trapper homepage
    re_path(r"^$", accounts_views.view_index, name="trapper_index"),
    # Media classification urls
    re_path(
        r"^media_classification/",
        include("trapper.apps.media_classification.urls", "media_classification"),
    ),
    # Research urls
    re_path(r"^research/", include("trapper.apps.research.urls")),
    # Storage urls
    re_path(r"^storage/", include("trapper.apps.storage.urls", "storage")),
    # Messaging urls
    re_path(r"^messaging/", include("trapper.apps.messaging.urls")),
    # Accounts urls
    re_path("", include("django.contrib.auth.urls")),
    re_path(r"^accounts/", include("trapper.apps.accounts.urls")),
    re_path(r"^account/", include("allauth.urls")),
    # GeoMap urls
    re_path(r"^geomap/", include("trapper.apps.geomap.urls")),
    # Comments
    re_path(r"^comments/", include("trapper.apps.comments.urls")),
    # Extra tables
    re_path(r"^tables/", include("trapper.apps.extra_tables.urls")),
    # Sendfile urls
    re_path(r"^serve/", include("trapper.apps.sendfile.urls")),
    re_path(r"^grappelli/", include("grappelli.urls")),
    re_path(r"^admin/", admin.site.urls),
    # REST API Swagger docs
    re_path(
        r"^docs/api/swagger(?P<format>\.json|\.yaml)$",
        swagger_schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^docs/api/$",
        swagger_schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^docs/api/redoc/$",
        swagger_schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # Debug Toolbar
    re_path(r"^__debug__/", include(debug_toolbar.urls)),
    # JupyterLite urls
    re_path(r"^jupyterlite/", include("trapper.apps.jupyterlite.urls")),
]

# Umap patterns
urlpatterns += (
    re_path(
        r"^map/(?P<pk>\d+)/geojson/$",
        umap_views.MapViewGeoJSON.as_view(),
        name="map_geojson",
    ),
    re_path(
        r"^map/anonymous-edit/(?P<signature>.+)$",
        umap_views.MapAnonymousEditUrl.as_view(),
        name="map_anonymous_edit_url",
    ),
    re_path(
        r"^pictogram/json/$",
        umap_views.PictogramJSONList.as_view(),
        name="pictogram_list_json",
    ),
    re_path(
        r"^$",
        accounts_views.view_index,
        name="user_dashboard",
    ),
)
urlpatterns += decorated_patterns(
    cache_control(must_revalidate=True),
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/$",
        umap_views.DataLayerView.as_view(),
        name="datalayer_view",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/versions/$",
        umap_views.DataLayerVersions.as_view(),
        name="datalayer_versions",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/(?P<name>[_\w]+.geojson)$",
        umap_views.DataLayerVersion.as_view(),
        name="datalayer_version",
    ),  # noqa
)
urlpatterns += decorated_patterns(
    [ensure_csrf_cookie],
    re_path(
        r"^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$", umap_views.MapView.as_view(), name="map"
    ),  # noqa
    re_path(r"^map/new/$", umap_views.MapNew.as_view(), name="map_new"),
)
urlpatterns += decorated_patterns(
    [login_required_if_not_anonymous_allowed, never_cache],
    re_path(r"^map/create/$", umap_views.MapCreate.as_view(), name="map_create"),
)
urlpatterns += decorated_patterns(
    [map_permissions_check, never_cache],
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/settings/$",
        umap_views.MapUpdate.as_view(),
        name="map_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/permissions/$",
        umap_views.UpdateMapPermissions.as_view(),
        name="map_update_permissions",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/owner/$",
        umap_views.AttachAnonymousMap.as_view(),
        name="map_attach_owner",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/delete/$",
        umap_views.MapDelete.as_view(),
        name="map_delete",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/clone/$",
        umap_views.MapClone.as_view(),
        name="map_clone",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/create/$",
        umap_views.DataLayerCreate.as_view(),
        name="datalayer_create",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$",
        umap_views.DataLayerUpdate.as_view(),
        name="datalayer_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$",
        umap_views.DataLayerDelete.as_view(),
        name="datalayer_delete",
    ),
)
urlpatterns += i18n_patterns(
    re_path(
        r"^showcase/$",
        cache_page(24 * 60 * 60)(umap_views.showcase),
        name="maps_showcase",
    ),
    re_path(r"^search/$", umap_views.search, name="search"),
    re_path(r"^about/$", umap_views.about, name="about"),
    re_path(r"^user/(?P<username>.+)/$", umap_views.user_maps, name="user_maps"),
)

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + []
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/index_bulk.html
{% extends "media_classification/index.html" %}

{% load common_tags %}
{% load user_comments %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}

{% block data_app %}classification::bulk{% endblock data_app %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block scripts_append %}
{% endblock scripts_append %}

{% block section_content %}

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h2 class="panel-title">
          <span class="fa fa-flask"></span> <a href="{% url 'research:project_detail' pk=project.research_project.pk %}">{{ project.research_project.acronym }}</a> >
          <span class="fa fa-cubes"></span> <a href="{% url 'media_classification:project_detail' pk=project.pk %}">{{ project.name }}</a> >
          <span class="fa fa-database"></span> <a href="{% url 'storage:collection_detail' pk=storage_collection.pk %}">{{ storage_collection.name }}</a>
	</h2>
      </div>
    </div>
  </div>
</div>

<div ng-controller="SequenceController"
     ng-init="load('{% url "media_classification:api-classification-resources-list" collection.pk %}?project={{ project.pk }}', '{% url "media_classification:api-sequence-list" %}?collection={{ collection.pk }}', {{ collection.pk }})">
  <!-- res, seq, collection_pk !-->

{% include 'media_classification/classifications/classify/sequence_box_bulk.html' %}


{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/sequence_box_bulk.html
{% load i18n %}

<div class="row">
  <div class="col-md-12" ng-cloak>

    <div class="row">
      <div class="col-md-12">
	<div class="panel panel-default">
	  
	  <div class="panel-heading">
	    <action-classify-form-modal class="btn-success" id="btn-classify" ng-click="execute('{% url "media_classification:classify_form" project.pk %}')">
	    </action-classify-form-modal>
	    <button id="btn-clear-selection" type="button" class="btn btn-danger" ng-click="clearSelection()">{% trans "Clear selections" %}
	    </button>
            <div class="pull-right">
              {% trans "Total in collection" %}: <strong>{{ total_collection }}</strong> |
              {% trans "Filtered" %}: <strong>{[{ data.pagination.count }]}</strong> |
              {% trans "Selected" %} <strong>{[{ data.selectedCounter }]}</strong>
            </div>
	  </div>
	  
	  <div class="panel-body">	  
	    <div id="lightgallery" class="col-md-12">
	      <div class="panel-sequence" style="min-height:200px"
	    	   ng-repeat="record in data.records track by record.pk"
	    	   ng-click="select($event, record)"
	    	   ng-class="{'selected': record.$selected, 'approved': record.classification_data.is_approved, 'current': record.pk === current }">
		<div class="panel-seq-list" ng-if="record.sequence" ng-click="sequenceSelected($event, record.sequence)" title="{% trans "Click to select" %}">
	    	  <span class="badge">{[{ record.sequence }]}</span>
		</div>
		<span
		  ng-if="record.classification_data.has_bboxes_classified && !record.classification_data.has_bboxes_approved"
		  class="badge badge-bboxes-classified"
		  title="{% trans "Bboxes" %}">
		  <span class="fa fa-hand-pointer-o"></span>
		</span>
		<span
		  ng-if="record.classification_data.has_bboxes_approved"
		  class="badge badge-bboxes-approved"
		  title="{% trans "Bboxes" %}">
		  <span class="fa fa-hand-pointer-o"></span>
		</span>
		<span
		  ng-if="record.classification_data.is_classified && !record.classification_data.is_approved"
		  class="badge badge-classified"
		  title="{% trans "Classified" %}">
		  <span class="fa fa-check"></span>
		</span>
		<span ng-if="record.classification_data.is_approved" class="badge badge-approved" title="{% trans "Approved" %}">
		  <span class="fa fa-check"></span>
		</span>
		<div
		  ng-if="record.resource_type == 'I'"
		  data-src="{[{ record.url }]}"
		  class="img-thumbnail"
		  ng-click="openGallery($event)"
		  title="{[{ record.name }]} {[{ record.date_recorded | dateTZ: dateFormat.table }]}">
	      	  <img ng-src="{[{ record.thumbnail_url }]}"/>
		</div>
		<div ng-if="record.resource_type == 'V'" style="display:none;" id="video{[{ $index }]}">
	      	  <video class="lg-video-object lg-html5 video-js" controls preload="none">
	      	    <source src="{[{ record.url }]}#t=0.1" type="{[{ record.mime }]}">
	      	  </video>
		</div>
		<div
		  ng-if="record.resource_type == 'V'"
		  data-html="#video{[{ $index }]}"
		  class="img-thumbnail"
		  ng-click="openGallery($event)"
		  title="{[{ record.name }]} {[{ record.date_recorded | dateTZ: dateFormat.table }]}">
	      	  <img ng-src="{[{ record.thumbnail_url }]}"/>
		</div>
		<ul>
	      	  <li>
	      	    <span ng-bind-html="record.resource_type | typesIcon"></span> {[{ record.name }]}
	      	  </li>
	      	  <li>{[{ record.date_recorded | dateTZ: dateFormat.simple }]}</li>
		</ul>
		<a ng-href="{[{ record.classification_data.url }]}" class="btn btn-xs btn-default btn-inline">
	      	  <span class="fa fa-eye"></span> {% trans "Details" %}
		</a>
		<action-classify-form-modal class="btn-xs" ng-click="execute('{% url "media_classification:classify_form" project.pk %}', record)">
		</action-classify-form-modal>
              </div>
	    </div>
	  </div>
	  
	  <div class="panel-footer form-inline">
	    <div class="form-group">
	      {% include 'media_classification/classifications/classify/pagination.html' %}
	    </div>
	  </div>
	      
	</div>

	<div class="row">
	  <!-- filters -->
	  <div class="col-md-8">
	    <div class="panel panel-default">
	      <div class="panel-heading">
		<h2 class="panel-title">{% trans "Filters" %}</h2>
	      </div>
	      <div class="panel-body">
		<div class="form-group form-filter-full">
		  <label for="deployments" class="control-label">{% trans "Deployments" %}</label>
		  <input
		    type="text"
		    class="select2ajax"
		    id="deployment"
		    ng-model="filters.deployment"
		    filter-tokens="deployment"
		    filter-api-url='{% url "geomap:api-deployment-list" %}?classification_project={{ project.pk }}'
		    filter-text-label="deployment_id"
		    filter-id-label="pk"
		    filter-multiple="false"
		    filter-service="filter">
		  </input>
		</div>
		<div class="form-group form-filter-full">
		  <label for="species" class="control-label">{% trans "Species" %}</label>
		  <input
		    type="text"
		    class="select2ajax"
		    multiple="true"
		    id="species"
		    ng-model="filters.species"
		    filter-tokens="species"
		    filter-api-url='{% url "extra_tables:api-species-list" %}'
		    filter-text-label="__str__"
		    filter-id-label="pk"
		    filter-multiple="true"
		    filter-service="filter">
                  </input>
		</div>
		<div class="form-group form-filter-wide">
		  <label for="type" class="control-label">{% trans "File type" %}</label>
		  <select
		    id="type"
		    class="form-control"
		    filter-text="ftype"
		    filter-service="filter"
		    ng-model="filters.ftype"
		    ng-options="option.value as option.label for option in optionList.media">
		  </select>
		</div>
		<div class="form-group form-filter-wide">
		  <label for="bboxes" class="control-label">{% trans "Bboxes" %}</label>
		  <select
		    id="bboxes"
		    class="form-control"
		    filter-text="bboxes"
		    filter-service="filter"
		    ng-model="filters.bboxes"
		    ng-options="option.value as option.label for option in optionList.bool">
		  </select>
		</div>
		<div class="form-group form-filter-wide">
		  <label for="classified" class="control-label">{% trans "Classified" %}</label>
		  <select
		    id="classified"
		    class="form-control"
		    filter-text="classified"
		    filter-service="filter"
		    ng-model="filters.classified"
		    ng-options="option.value as option.label for option in optionList.bool">
		  </select>
		</div>
		<div class="form-group form-filter-wide">
		  <label for="classified" class="control-label">{% trans "Classified AI" %}</label>
		  <select
		    id="classified_ai"
		    class="form-control"
		    filter-text="classified_ai"
		    filter-service="filter"
		    ng-model="filters.classified_ai"
		    ng-options="option.value as option.label for option in optionList.bool">
		  </select>
		</div>
		<div class="form-group form-filter-wide">
		  <label for="status" class="control-label">{% trans "Approved" %}</label>
		  <select
		    id="status"
		    class="form-control"
		    filter-text="status"
		    filter-service="filter"
		    ng-model="filters.status"
		    ng-options="option.value as option.label for option in optionList.bool">
		  </select>
		</div>
		<div class="form-group form-filter-wide">
		  <label for="classified" class="control-label">{% trans "Approved AI" %}</label>
		  <select
		    id="status_ai"
		    class="form-control"
		    filter-text="status_ai"
		    filter-service="filter"
		    ng-model="filters.status_ai"
		    ng-options="option.value as option.label for option in optionList.bool">
		  </select>
		</div>
        <div class="form-group form-filter-wide">
          <label for="classified" class="control-label">{% trans "Observation type" %}</label>
          <select
                  id="observation_type"
                  class="form-control"
                  filter-text="observation_type"
                  filter-service="filter"
                  ng-model="filters.observation_type"
                  ng-options="option.value as option.label for option in optionList.observation_type">
          </select>
        </div>
		<button type="button" class="btn btn-success" ng-click="reload()">
		  <span class="fa fa-search"></span> {% trans "Filter" %} {{ grid_context.model_name }}
		</button>
		<div class="btn-selects">
		  <button type="button" class="btn btn-default" ng-click="saveFilters()">{% trans "Save filters" %}</button>
		  <button type="button" class="btn btn-warning" ng-click="filter.clearFilters()">{% trans "Clear filters" %}</button>
		  <button
		    type="button"
		    class="btn btn-warning"
		    ng-click="load_resources(data.request.urlRes, {clear_cache: true}, true)">{% trans "Clear cache" %}
		  </button>

		</div>
	      </div>
	    </div>
	  </div>
	  
	  {% if project.is_sequencing_enabled %}
	  <div class="col-md-4">
	    <div class="panel panel-default">
	      <div class="panel-heading">
		<h2 class="panel-title">{% trans "Sequence" %}</h2>
	      </div>

	      <div class="panel-body">
		<div class="form-group">
		  <select
		    id="sequence-picker"
		    class="select2"
		    ng-model="sequences.selected"
		    ng-change="sequenceChanged()"
		    ng-options="seq as 'Sequence: '+seq.sequence_id for seq in sequences.original track by seq.sequence_id">
		  </select>
		  {% if collection.is_sequencing_enabled %}
		</div>
		<div>
		  <button type="button" class="btn btn-primary" ng-click="saveSequence('{% url "media_classification:sequence_change" %}')">
		    {% trans "Save sequence" %}
		  </button>
		  <button type="button" class="btn btn-danger" ng-click="deleteSequence('{% url "media_classification:sequence_delete" %}')">
		    {% trans "Delete" %}
		  </button>
		</div>
		{% endif %}
	      </div>
	    </div>
	  </div>
	  {% endif %}
	</div>
	
      </div>
    </div>
  </div>
</div>