trapper/trapper-project/trapper/apps/messaging/urls.py
from django.urls import reverse_lazy, re_path
from django.views.generic import RedirectView
from trapper.apps.messaging import views as messaging_views

app_name = "messaging"

urlpatterns = [
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("messaging:message_inbox")),
        name="index",
    ),
    re_path(
        r"message/detail/(?P<hashcode>\w+)/$",
        messaging_views.view_message_detail,
        name="message_detail",
    ),
    re_path(
        r"message/inbox/$", messaging_views.view_message_inbox, name="message_inbox"
    ),
    re_path(
        r"message/outbox/$", messaging_views.view_message_outbox, name="message_outbox"
    ),
    re_path(
        r"message/create/$", messaging_views.view_message_create, name="message_create"
    ),
    re_path(
        r"collection-request/list/$",
        messaging_views.view_collection_request_list,
        name="collection_request_list",
    ),
    re_path(
        r"collection-request/resolve/(?P<pk>\d+)/$",
        messaging_views.view_collection_request_resolve,
        name="collection_request_resolve",
    ),
    re_path(
        r"collection-request/revoke/(?P<pk>\d+)/$",
        messaging_views.view_collection_request_revoke,
        name="collection_request_revoke",
    ),
    re_path(
        r"collection-request/delete/(?P<pk>\d+)/$",
        messaging_views.view_collection_request_delete,
        name="collection_request_delete",
    ),
]

trapper/trapper-project/trapper/apps/research/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include
from django.urls import reverse_lazy, re_path
from django.views.generic import RedirectView

from rest_framework.routers import DefaultRouter

from trapper.apps.research.views import api as api_views
from trapper.apps.research.views import research as research_views

app_name = "research"

router = DefaultRouter(trailing_slash=False)
router.register(
    r"projects", api_views.ResearchProjectViewSet, basename="api-research-project"
)
router.register(
    r"project/(?P<project_pk>\d+)/collections",
    api_views.ResearchProjectCollectionViewSet,
    basename="api-research-project-collection",
)

urlpatterns = [
    re_path(r"^api/", include(router.urls)),
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("research:project_list")),
        name="project_index",
    ),
]

urlpatterns += [
    re_path(
        r"project/list/$",
        research_views.view_research_project_list,
        name="project_list",
    ),
    re_path(
        r"project/detail/(?P<pk>\d+)/$",
        research_views.view_research_project_detail,
        name="project_detail",
    ),
    re_path(
        r"project/create/$",
        research_views.view_research_project_create,
        name="project_create",
    ),
    re_path(
        r"project/update/(?P<pk>\d+)/$",
        research_views.view_research_project_update,
        name="project_update",
    ),
    re_path(
        r"project/delete/(?P<pk>\d+)/$",
        research_views.view_research_project_delete,
        name="project_delete",
    ),
    re_path(
        r"^project/delete/$",
        research_views.view_research_project_delete,
        name="project_delete_multiple",
    ),
    re_path(
        r"project/collection/add/$",
        research_views.view_research_project_collection_add,
        name="project_collection_add",
    ),
    re_path(
        r"^project/collection/delete/$",
        research_views.view_research_project_collection_delete,
        name="project_collection_delete_multiple",
    ),
    re_path(
        r"^project/collection/delete/(?P<pk>\d+)/$",
        research_views.view_research_project_collection_delete,
        name="project_collection_delete",
    ),
]

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy, re_path
from django.views.decorators.cache import cache_control, cache_page, never_cache
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from trapper.apps.accounts.views import accounts as accounts_views
from umap import views as umap_views
from umap.decorators import (
    map_permissions_check,
    login_required_if_not_anonymous_allowed,
)
from umap.utils import decorated_patterns

admin.autodiscover()


swagger_schema_view = get_schema_view(
    openapi.Info(
        title="TRAPPER API",
        default_version="v1",
        description="",
        terms_of_service="terms of service",
        contact=openapi.Contact(email="contact@os-conservation.org"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=[permissions.IsAuthenticated],
)


urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    re_path(
        r"^account/inactive/$",
        RedirectView.as_view(url=reverse_lazy("trapper_index")),
        name="account_inactive",
    ),
    # Trapper homepage
    re_path(r"^$", accounts_views.view_index, name="trapper_index"),
    # Media classification urls
    re_path(
        r"^media_classification/",
        include("trapper.apps.media_classification.urls", "media_classification"),
    ),
    # Research urls
    re_path(r"^research/", include("trapper.apps.research.urls")),
    # Storage urls
    re_path(r"^storage/", include("trapper.apps.storage.urls", "storage")),
    # Messaging urls
    re_path(r"^messaging/", include("trapper.apps.messaging.urls")),
    # Accounts urls
    re_path("", include("django.contrib.auth.urls")),
    re_path(r"^accounts/", include("trapper.apps.accounts.urls")),
    re_path(r"^account/", include("allauth.urls")),
    # GeoMap urls
    re_path(r"^geomap/", include("trapper.apps.geomap.urls")),
    # Comments
    re_path(r"^comments/", include("trapper.apps.comments.urls")),
    # Extra tables
    re_path(r"^tables/", include("trapper.apps.extra_tables.urls")),
    # Sendfile urls
    re_path(r"^serve/", include("trapper.apps.sendfile.urls")),
    re_path(r"^grappelli/", include("grappelli.urls")),
    re_path(r"^admin/", admin.site.urls),
    # REST API Swagger docs
    re_path(
        r"^docs/api/swagger(?P<format>\.json|\.yaml)$",
        swagger_schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^docs/api/$",
        swagger_schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^docs/api/redoc/$",
        swagger_schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # Debug Toolbar
    re_path(r"^__debug__/", include(debug_toolbar.urls)),
    # JupyterLite urls
    re_path(r"^jupyterlite/", include("trapper.apps.jupyterlite.urls")),
]

# Umap patterns
urlpatterns += (
    re_path(
        r"^map/(?P<pk>\d+)/geojson/$",
        umap_views.MapViewGeoJSON.as_view(),
        name="map_geojson",
    ),
    re_path(
        r"^map/anonymous-edit/(?P<signature>.+)$",
        umap_views.MapAnonymousEditUrl.as_view(),
        name="map_anonymous_edit_url",
    ),
    re_path(
        r"^pictogram/json/$",
        umap_views.PictogramJSONList.as_view(),
        name="pictogram_list_json",
    ),
    re_path(
        r"^$",
        accounts_views.view_index,
        name="user_dashboard",
    ),
)
urlpatterns += decorated_patterns(
    cache_control(must_revalidate=True),
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/$",
        umap_views.DataLayerView.as_view(),
        name="datalayer_view",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/versions/$",
        umap_views.DataLayerVersions.as_view(),
        name="datalayer_versions",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/(?P<name>[_\w]+.geojson)$",
        umap_views.DataLayerVersion.as_view(),
        name="datalayer_version",
    ),  # noqa
)
urlpatterns += decorated_patterns(
    [ensure_csrf_cookie],
    re_path(
        r"^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$", umap_views.MapView.as_view(), name="map"
    ),  # noqa
    re_path(r"^map/new/$", umap_views.MapNew.as_view(), name="map_new"),
)
urlpatterns += decorated_patterns(
    [login_required_if_not_anonymous_allowed, never_cache],
    re_path(r"^map/create/$", umap_views.MapCreate.as_view(), name="map_create"),
)
urlpatterns += decorated_patterns(
    [map_permissions_check, never_cache],
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/settings/$",
        umap_views.MapUpdate.as_view(),
        name="map_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/permissions/$",
        umap_views.UpdateMapPermissions.as_view(),
        name="map_update_permissions",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/owner/$",
        umap_views.AttachAnonymousMap.as_view(),
        name="map_attach_owner",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/delete/$",
        umap_views.MapDelete.as_view(),
        name="map_delete",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/clone/$",
        umap_views.MapClone.as_view(),
        name="map_clone",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/create/$",
        umap_views.DataLayerCreate.as_view(),
        name="datalayer_create",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$",
        umap_views.DataLayerUpdate.as_view(),
        name="datalayer_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$",
        umap_views.DataLayerDelete.as_view(),
        name="datalayer_delete",
    ),
)
urlpatterns += i18n_patterns(
    re_path(
        r"^showcase/$",
        cache_page(24 * 60 * 60)(umap_views.showcase),
        name="maps_showcase",
    ),
    re_path(r"^search/$", umap_views.search, name="search"),
    re_path(r"^about/$", umap_views.about, name="about"),
    re_path(r"^user/(?P<username>.+)/$", umap_views.user_maps, name="user_maps"),
)

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + []
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

trapper/trapper-project/trapper/apps/messaging/views.py
# -*- coding: utf-8 -*-
"""Module that contains logic for working with messaging application"""
from braces.views import UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect
from django.views import generic

from trapper.apps.common.views import (
    HashedDetailView,
    LoginRequiredMixin,
    BaseDeleteView,
)
from trapper.apps.messaging.forms import MessageForm
from trapper.apps.messaging.models import Message, CollectionRequest
from trapper.apps.messaging.taxonomies import MessageType


class MessageDetailView(LoginRequiredMixin, UserPassesTestMixin, HashedDetailView):
    """
    View used to show details of given message.
    Before page with message is shown, message is tested if currently logged in
    user have proper rights
    """

    model = Message

    raise_exception = True

    def test_func(self, user):
        """Check if user have enough permissions to display messsage"""
        return self.get_object().can_detail(user=user)

    def get_object(self, *args, **kwargs):
        """Get message by given hashcode and mark it as received"""
        message = super(MessageDetailView, self).get_object(*args, **kwargs)
        message = message.mark_received(user=self.request.user)
        return message


view_message_detail = MessageDetailView.as_view()


class MessageCreateView(LoginRequiredMixin, generic.CreateView):
    """View used for creating new messages"""

    form_class = MessageForm
    template_name = "messaging/message_create.html"

    def get_form_kwargs(self):
        """Update form `kwargs` so they contain current `request`"""
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        # We need this to exclude current user from receipient list
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        """If form is valid, then :class:`apps.messaging.models.Message`
        `user_from` attribute is updated with currently logged in user, and
        proper message is shown to user"""
        form.instance.user_from = self.request.user
        messages.add_message(self.request, messages.SUCCESS, _("Message has been sent"))
        return super(MessageCreateView, self).form_valid(form)

    def form_invalid(self, form):
        """If form is invalid, then error messages should be shown to user"""
        messages.add_message(
            self.request, messages.ERROR, _("Message form contains errors")
        )
        return super(MessageCreateView, self).form_invalid(form)


view_message_create = MessageCreateView.as_view()


class MessageListView(LoginRequiredMixin, generic.ListView):
    """Base class used for listing currently logged in user messages."""

    model = Message
    context_object_name = "message_list"
    is_inbox = None
    paginate_by = 20

    def get_context_data(self, **kwargs):
        """Additional information are required to display inbox or outbox
        messages"""
        context = super(MessageListView, self).get_context_data(**kwargs)
        context["is_inbox"] = self.is_inbox
        return context


view_message_list = MessageListView.as_view()


class MessageInboxView(MessageListView):
    """View used to display messages that were sent to currently logged in
    user"""

    template_name = "messaging/message_inbox.html"
    is_inbox = True

    def get_queryset(self):
        """Return all messsages assigned to user"""
        return self.request.user.received_messages.exclude(
            message_type__in=[
                MessageType.COLLECTION_REQUEST,
                MessageType.RESOURCE_REQUEST,
            ]
        ).select_related("user_from", "user_from__userprofile")


view_message_inbox = MessageInboxView.as_view()


class MessageOutboxView(MessageListView):
    """View used to display messages that were sent by currently logged in
    user"""

    template_name = "messaging/message_outbox.html"
    is_inbox = False

    def get_queryset(self):
        """Return all messages that user sent"""
        return self.request.user.sent_messages.all()


view_message_outbox = MessageOutboxView.as_view()


class CollectionRequestListView(LoginRequiredMixin, generic.ListView):
    """View used to display collection requests that were sent to currently
    logged in user"""

    context_object_name = "collection_requests"
    paginate_by = 20

    model = CollectionRequest
    template_name = "messaging/collection_request_list.html"

    def get_queryset(self):
        """Return all collection access requests. If request was resolved
        then 'resolve' link will be unavailable"""
        return (
            self.request.user.collection_requests.all()
            .select_related(
                "project", "message__user_from", "message__user_from__userprofile"
            )
            .prefetch_related("collections")
        )


view_collection_request_list = CollectionRequestListView.as_view()


class BaseResolveRequestView(
    LoginRequiredMixin, UserPassesTestMixin, generic.DetailView
):
    """
    Base class that holds logic responsible for resolving access requests
    """

    http_method_names = ["post"]
    redirect_url = None

    raise_exception = True

    def test_func(self, user):
        """Resolving is allowed only for recipients of requests"""
        return self.get_object().user == user

    def post(self, request, *args, **kwargs):
        """Approve or reject access to resources or collections"""
        obj = self.get_object()

        is_approved = "yes" in self.request.POST
        obj.resolve_access(user=request.user, is_approved=is_approved)
        return redirect(reverse(self.redirect_url))


class ResolveCollectionRequestView(BaseResolveRequestView):
    """View used to resolve access to collections requests"""

    model = CollectionRequest
    redirect_url = "messaging:collection_request_list"


view_collection_request_resolve = ResolveCollectionRequestView.as_view()


class DeleteCollectionRequestView(BaseDeleteView):
    model = CollectionRequest
    redirect_url = "messaging:collection_request_list"


view_collection_request_delete = DeleteCollectionRequestView.as_view()


class BaseRevokeRequestView(
    LoginRequiredMixin, UserPassesTestMixin, generic.DetailView
):
    """Base class used for revoking access for requests that were approved"""

    http_method_names = ["post"]
    redirect_url = None

    raise_exception = True

    def test_func(self, user):
        """Resolving is allowed only for recipients of requests"""
        return self.get_object().user == user

    def post(self, request, *args, **kwargs):
        """Revoke access rights to resources or collections"""
        obj = self.get_object()
        is_revoked = "yes" in self.request.POST

        if is_revoked:
            obj.resolve_revoke(user=request.user)
        return redirect(reverse(self.redirect_url))


class RevokeCollectionRequestView(BaseRevokeRequestView):
    """View used for revoking access to collections"""

    model = CollectionRequest
    redirect_url = "messaging:collection_request_list"


view_collection_request_revoke = RevokeCollectionRequestView.as_view()

trapper/trapper-project/trapper/apps/messaging/templates/messaging/collection_request_list.html
{% extends "messaging/index.html" %}

{% load i18n %}

{% block messaging_collection_request %}primary{% endblock %}
{% block data_app %}message::preview{% endblock %}

{% block section_content %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">{% trans "Messages" %}</h2>
    </div>

    {% if collection_requests %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th>{% trans "Sender" %}</th>
        <th>{% trans "Message" %}</th>
        <th>{% trans "Research project" %}</th>
        <th>{% trans "Collection" %}</th>
        <th>{% trans "Action" %}</th>
	<th></th>
      </tr>
      </thead>

      <tbody>
      {% for collection_request in collection_requests %}
        <tr>
          <td><a href="{{ collection_request.message.user_from.userprofile.get_absolute_url }}">{% pretty_username collection_request.message.user_from %}</a></td>
          <td>
            <span class="fa fa-circle{% if not collection_request.message.is_new %}-o{% endif %}"></span>
            <a href="{{ collection_request.message.get_absolute_url }}" >{% trans "View Message" %}
            </a>
          </td>
          {% with collection_request.project as project %}
            <td>
              <a href="{% url "research:project_detail" project.pk %}">{{ project.name }}</a></td>
          {% endwith %}
          <td>
            {% for collection in collection_request.collections.all %}
              <a href="{% url "storage:collection_detail" collection.pk %}">{{ collection.name }}</a>
            {% endfor %}
          </td>

          <td>
            {% if collection_request.resolved_at %}
              {% if collection_request.is_approved %}<b class="text-green">{% trans "Approved" %}</b>{% else %}<b class="text-red">{% trans "Rejected" %}</b>{% endif %} at {{ collection_request.resolved_at|date:"d.m.Y, H:i" }}
            {% else %}
              <button type="button" class="btn btn-link" data-resolve="{% url 'messaging:collection_request_resolve' collection_request.pk %}" data-type="collection">{% trans "Resolve" %}</button>
              {% endif %}
            {% if collection_request.is_approved %}
              <p><button type="button" class="btn btn-link" data-revoke="{% url 'messaging:collection_request_revoke' collection_request.pk %}" data-type="collection">{% trans "Revoke" %}</button></p>
            {% endif %}
          </td>
	  <td>
	    {% if not collection_request.is_approved %}
	    <a href="{% url 'messaging:collection_request_delete' collection_request.pk %}" class="btn btn-danger"><span class="fa fa-trash-o"></span></a>
	    {% endif %}
	  </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    {% else %}
      <div class="alert alert-warning ng-binding">
        <span class="fa fa-info"></span> {% trans "No collection requests available." %}
      </div>

    {% endif %}
  </div>

{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/index.html
{% extends "index.html" %}

{% load i18n common_tags %}

{% block data_app %}messaging:main{% endblock %}

{% block main_menu %}{% nav_active 'menu_messages' %}{{ block.super }}{% endblock main_menu %}

{% block content %}
  <ul class="nav nav-pills">
    <div class="nav-secondary">
      <a href="{% url "messaging:message_inbox" %}" class="btn btn-{% block messaging_message_inbox %}default{% endblock %}">{% trans "Inbox " %}<span class="badge">{{ user.userprofile.count_unread_messages }}/{{ user.userprofile.count_inbox_messages }}</span></a>
      <a href="{% url "messaging:message_outbox" %}" class="btn btn-{% block messaging_message_outbox %}default{% endblock %}">{% trans "Outbox " %}<span class="badge">{{ user.sent_messages.all.count }}</span></a>
      <a href="{% url "messaging:collection_request_list" %}" class="btn btn-{% block messaging_collection_request %}default{% endblock %}">{% trans "Collection requests " %}<span class="badge">{{ user.userprofile.awaiting_collection_requests }}</span></a>
      <a href="{% url "messaging:message_create" %}" class="btn btn-success pull-right"><span class="fa fa-pencil"></span> {% trans "New message" %}</a>
    </div>

  </ul>
  <div class="pill-content">
    {% block section_content %}{% endblock section_content %}
  </div>
{% endblock content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_create.html
{% extends "messaging/index.html" %}

{% load i18n crispy_forms_tags %}

{% block messaging_message_create %}primary{% endblock %}
{% block data_app %}message::new{% endblock %}

{% block section_content %}
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">{% trans "New message" %}</h2>
      </div>

      <form action="." method="post" class="panel-body" enctype="multipart/form-data">
        {% crispy form form.helper %}
        <fieldset>
          <button type="submit" class="btn btn-primary">{% trans "Send" %}</button>
        </fieldset>
      </form>
      
    </div>
  </div>

{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_detail.html
{% extends "messaging/index.html" %}

{% load i18n %}

{% block messaging_message_inbox %}{% if message.is_inbox %}primary{% else %}default{% endif %}{% endblock %}
{% block messaging_message_outbox %}{% if message.is_outbox %}primary{% else %}default{% endif %}{% endblock %}
{% block messaging_collection_request %}{% if message.is_collection_request %}primary{% else %}default{% endif %}{% endblock %}
{% block messaging_resource_request %}{% if message.is_resource_request %}primary{% else %}default{% endif %}{% endblock %}

{% block data_app %}message::preview{% endblock %}

{% block section_content %}
  {% with message.user_from as sender %}
  {% with sender.userprofile.get_absolute_url as sender_profile %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">{% trans "Title: " %}<strong>{{ message.subject|safe }}</strong></h2>
    </div>

    <div class="panel-body">
      {{ message.text|safe}}
    </div>

    <div class="panel-footer">
      {% trans "Sender: " %}<strong><a href="{{ sender_profile }}">{% pretty_username sender %}</a></strong>
    </div>
    <div class="panel-footer">
      {% trans "Date: " %}<strong>{{ message.date_sent|date:"d.m.Y, H:i" }}</strong>
    </div>
  </div>

  {% endwith %}
  {% endwith %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_inbox.html
{% extends "messaging/index.html" %}

{% block messaging_message_inbox %}primary{% endblock %}
{% block data_app %}message::list{% endblock %}

{% block section_content %}
  {% include "messaging/message_list.html" %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_list.html
{% load i18n %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">{% trans "Messages" %}</h2>
  </div>

  {% if message_list %}
  <table class="table table-striped">
    <thead>
    <tr>
      <th>{% trans "Subject" %}</th>
      <th>{% trans "Date" %}</th>
      <th>{% trans "Sender" %}</th>
    </tr>
    </thead>

    <tbody>
    {% for message in message_list %}
    <tr>
      <td>
        <span class="fa fa-circle{% if not is_inbox or not message.is_new %}-o{% endif %}"></span>
        <a href="{% url "messaging:message_detail" message.hashcode %}">{{ message.subject|safe }}</a>
      </td>
      <td>{{ message.date_sent|date:"d.m.Y, H:i" }}</td>
      <td><a href="{{ message.user_from.userprofile.get_absolute_url }}">{% pretty_username message.user_from %}</a></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <div class="alert alert-warning ng-binding">
      <span class="fa fa-info"></span> {% trans "No messages available." %}
    </div>
  {% endif %}
</div>

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_outbox.html
{% extends "messaging/index.html" %}

{% block messaging_message_outbox %}primary{% endblock %}
{% block data_app %}message::list{% endblock %}

{% block section_content %}
  {% include "messaging/message_list.html" %}
{% endblock section_content %}