trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import include
from django.urls import reverse_lazy, path, re_path
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

import trapper.apps.media_classification.views.ai_classifications
from trapper.apps.media_classification.views import (
    api as classification_api_views,
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    ai_classifications as ai_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views,
)

app_name = "media_classification"

router = DefaultRouter(trailing_slash=False)

router.register(
    r"classificators",
    classification_api_views.ClassificatorViewSet,
    basename="api-classificator",
)

router.register(
    r"user-classifications",
    classification_api_views.UserClassificationViewSet,
    basename="api-user-classification",
)

router.register(
    r"classifications",
    classification_api_views.ClassificationViewSet,
    basename="api-classification",
)

router.register(
    r"ai-classifications",
    classification_api_views.AIClassificationViewSet,
    basename="api-ai-classification",
)

router.register(
    r"classifications_map",
    classification_api_views.ClassificationMapViewSet,
    basename="api-classification-map",
)

router.register(
    r"projects",
    classification_api_views.ClassificationProjectViewSet,
    basename="api-classification-project",
)

router.register(
    r"project/(?P<project_pk>\d+)/collections",
    classification_api_views.ClassificationProjectCollectionViewSet,
    basename="api-classification-project-collection",
)

router.register(
    r"sequences", classification_api_views.SequenceViewSet, basename="api-sequence"
)

router.register(
    r"collection/(?P<collection_pk>\d+)/resources/$",
    classification_api_views.ClassificationResourcesViewSet,
    basename="api-classification-resources",
)

urlpatterns = [
    re_path(r"^api/", include(router.urls)),
    re_path(
        r"^api/classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsView.as_view(),
        name="api-classification-results",
    ),
    re_path(
        r"^api/ai-classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.AIClassificationResultsView.as_view(),
        name="api-ai-classification-results",
    ),
    re_path(
        r"^api/classifications/results/agg/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsAggView.as_view(),
        name="api-classification-results-agg",
    ),
    re_path(
        r"^api/classifications/import/",
        classification_api_views.ClassificationImport.as_view(),
        name="api-classification-import",
    ),
    re_path(
        r"^api/media/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationProjectMediaTableView.as_view(),
        name="api-media-export",
    ),
    re_path(
        r"^api/package/(?P<project_pk>\d+)/",
        classification_api_views.ResultsDataPackageAPIView.as_view(),
        name="api-package-export",
    ),
    path(
        "api/classify/ai/callback/<str:ai_provider_token>/",
        classification_api_views.classify_ai_callback,
        name="api-classify-ai-callback",
    ),
    path(
        "api/classify/ai/classification_extra/<str:ai_provider_token>/<str:classification_job_id>/<str:resource_name>/",
        classification_api_views.classify_ai_extra_resource,
        name="api-classify-ai-extra",
    ),
]

urlpatterns += [
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("media_classification:project_list")),
        name="project_index",
    ),
    # Project views
    re_path(r"project/list/$", projects_views.view_project_list, name="project_list"),
    re_path(
        r"project/detail/(?P<pk>\d+)/$",
        projects_views.view_project_detail,
        name="project_detail",
    ),
    re_path(
        r"project/create/$", projects_views.view_project_create, name="project_create"
    ),
    re_path(
        r"project/update/(?P<pk>\d+)/$",
        projects_views.view_project_update,
        name="project_update",
    ),
    re_path(
        r"project/delete/(?P<pk>\d+)/$",
        projects_views.view_project_delete,
        name="project_delete",
    ),
    re_path(
        r"^project/delete/$",
        projects_views.view_project_delete,
        name="project_delete_multiple",
    ),
    re_path(
        r"project/collection/add/$",
        projects_views.view_project_collection_add,
        name="project_collection_add",
    ),
    re_path(
        r"project/collection/delete/(?P<pk>\d+)/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete",
    ),
    re_path(
        r"^project/collection/delete/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete_multiple",
    ),
    re_path(
        r"^project/collection/blur/$",
        projects_views.view_project_collection_blur_humans,
        name="project_collection_blur_humans",
    ),
    # Classificator views
    re_path(
        r"classificator/list/$",
        classificators_views.view_classificator_list,
        name="classificator_list",
    ),
    re_path(
        r"classificator/detail/(?P<pk>\d+)/$",
        classificators_views.view_classificator_detail,
        name="classificator_detail",
    ),
    re_path(
        r"classificator/create/$",
        classificators_views.view_classificator_create,
        name="classificator_create",
    ),
    re_path(
        r"classificator/update/(?P<pk>\d+)/$",
        classificators_views.view_classificator_update,
        name="classificator_update",
    ),
    re_path(
        r"classificator/clone/(?P<pk>\d+)/$",
        classificators_views.view_classificator_clone,
        name="classificator_clone",
    ),
    re_path(
        r"^classificator/delete/(?P<pk>\d+)/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete",
    ),
    re_path(
        r"^classificator/delete/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete_multiple",
    ),
    # Sequence views
    re_path(
        r"sequence/create/$",
        sequences_views.view_sequence_change,
        name="sequence_create",
    ),
    re_path(
        r"sequence/update/$",
        sequences_views.view_sequence_change,
        name="sequence_update",
    ),
    re_path(
        r"sequence/change/$",
        sequences_views.view_sequence_change,
        name="sequence_change",
    ),
    re_path(
        r"sequence/delete/$",
        sequences_views.view_sequence_delete,
        name="sequence_delete",
    ),
    re_path(
        r"^sequence/build/$", sequences_views.view_sequence_build, name="sequence_build"
    ),
    # Classification views
    re_path(
        r"^classification/overview/$",
        classifications_views.view_classification_overview,
        name="classification_overview",
    ),
    re_path(
        r"^classification/list/(?P<pk>\d+)/$",
        classifications_views.view_classification_list,
        name="classification_list",
    ),
    re_path(
        r"classification/import/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/import/(?P<pk>\d+)/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/export/(?P<pk>\d+)/$",
        classifications_views.view_classification_export,
        name="classification_export",
    ),
    re_path(
        r"classification/publish/$",
        classifications_views.view_classification_publish,
        name="classification_publish",
    ),
    re_path(
        r"classification/feedback/(?P<pk>\d+)/$",
        classifications_views.view_classification_feedback,
        name="classification_feedback",
    ),
    re_path(
        r"classification/export-agg/(?P<pk>\d+)/$",
        classifications_views.view_classification_export_agg,
        name="classification_export_agg",
    ),
    re_path(
        r"classification/importattrs/(?P<pk>\d+)/$",
        classifications_views.view_classification_import_attrs,
        name="classification_importattrs",
    ),
    re_path(
        r"^classification/delete/(?P<pk>\d+)/$",
        classifications_views.view_classification_delete,
        name="classification_delete",
    ),
    re_path(
        r"^classification/delete/$",
        classifications_views.view_classification_delete,
        name="classification_delete_multiple",
    ),
    re_path(
        r"^classification/bulk-update/$",
        classifications_views.view_classification_bulk_update,
        name="classification_bulk_update",
    ),
    re_path(
        r"classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$",
        classifications_views.view_classify_collection,
        name="classify_collection",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify_user",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    path(
        "classify/<int:pk>/ai/<int:ai_provider_id>/",

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy, re_path
from django.views.decorators.cache import cache_control, cache_page, never_cache
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from trapper.apps.accounts.views import accounts as accounts_views
from umap import views as umap_views
from umap.decorators import (
    map_permissions_check,
    login_required_if_not_anonymous_allowed,
)
from umap.utils import decorated_patterns

admin.autodiscover()


swagger_schema_view = get_schema_view(
    openapi.Info(
        title="TRAPPER API",
        default_version="v1",
        description="",
        terms_of_service="terms of service",
        contact=openapi.Contact(email="contact@os-conservation.org"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=[permissions.IsAuthenticated],
)


urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    re_path(
        r"^account/inactive/$",
        RedirectView.as_view(url=reverse_lazy("trapper_index")),
        name="account_inactive",
    ),
    # Trapper homepage
    re_path(r"^$", accounts_views.view_index, name="trapper_index"),
    # Media classification urls
    re_path(
        r"^media_classification/",
        include("trapper.apps.media_classification.urls", "media_classification"),
    ),
    # Research urls
    re_path(r"^research/", include("trapper.apps.research.urls")),
    # Storage urls
    re_path(r"^storage/", include("trapper.apps.storage.urls", "storage")),
    # Messaging urls
    re_path(r"^messaging/", include("trapper.apps.messaging.urls")),
    # Accounts urls
    re_path("", include("django.contrib.auth.urls")),
    re_path(r"^accounts/", include("trapper.apps.accounts.urls")),
    re_path(r"^account/", include("allauth.urls")),
    # GeoMap urls
    re_path(r"^geomap/", include("trapper.apps.geomap.urls")),
    # Comments
    re_path(r"^comments/", include("trapper.apps.comments.urls")),
    # Extra tables
    re_path(r"^tables/", include("trapper.apps.extra_tables.urls")),
    # Sendfile urls
    re_path(r"^serve/", include("trapper.apps.sendfile.urls")),
    re_path(r"^grappelli/", include("grappelli.urls")),
    re_path(r"^admin/", admin.site.urls),
    # REST API Swagger docs
    re_path(
        r"^docs/api/swagger(?P<format>\.json|\.yaml)$",
        swagger_schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^docs/api/$",
        swagger_schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^docs/api/redoc/$",
        swagger_schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # Debug Toolbar
    re_path(r"^__debug__/", include(debug_toolbar.urls)),
    # JupyterLite urls
    re_path(r"^jupyterlite/", include("trapper.apps.jupyterlite.urls")),
]

# Umap patterns
urlpatterns += (
    re_path(
        r"^map/(?P<pk>\d+)/geojson/$",
        umap_views.MapViewGeoJSON.as_view(),
        name="map_geojson",
    ),
    re_path(
        r"^map/anonymous-edit/(?P<signature>.+)$",
        umap_views.MapAnonymousEditUrl.as_view(),
        name="map_anonymous_edit_url",
    ),
    re_path(
        r"^pictogram/json/$",
        umap_views.PictogramJSONList.as_view(),
        name="pictogram_list_json",
    ),
    re_path(
        r"^$",
        accounts_views.view_index,
        name="user_dashboard",
    ),
)
urlpatterns += decorated_patterns(
    cache_control(must_revalidate=True),
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/$",
        umap_views.DataLayerView.as_view(),
        name="datalayer_view",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/versions/$",
        umap_views.DataLayerVersions.as_view(),
        name="datalayer_versions",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/(?P<name>[_\w]+.geojson)$",
        umap_views.DataLayerVersion.as_view(),
        name="datalayer_version",
    ),  # noqa
)
urlpatterns += decorated_patterns(
    [ensure_csrf_cookie],
    re_path(
        r"^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$", umap_views.MapView.as_view(), name="map"
    ),  # noqa
    re_path(r"^map/new/$", umap_views.MapNew.as_view(), name="map_new"),
)
urlpatterns += decorated_patterns(
    [login_required_if_not_anonymous_allowed, never_cache],
    re_path(r"^map/create/$", umap_views.MapCreate.as_view(), name="map_create"),
)
urlpatterns += decorated_patterns(
    [map_permissions_check, never_cache],
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/settings/$",
        umap_views.MapUpdate.as_view(),
        name="map_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/permissions/$",
        umap_views.UpdateMapPermissions.as_view(),
        name="map_update_permissions",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/owner/$",
        umap_views.AttachAnonymousMap.as_view(),
        name="map_attach_owner",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/delete/$",
        umap_views.MapDelete.as_view(),
        name="map_delete",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/clone/$",
        umap_views.MapClone.as_view(),
        name="map_clone",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/create/$",
        umap_views.DataLayerCreate.as_view(),
        name="datalayer_create",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$",
        umap_views.DataLayerUpdate.as_view(),
        name="datalayer_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$",
        umap_views.DataLayerDelete.as_view(),
        name="datalayer_delete",
    ),
)
urlpatterns += i18n_patterns(
    re_path(
        r"^showcase/$",
        cache_page(24 * 60 * 60)(umap_views.showcase),
        name="maps_showcase",
    ),
    re_path(r"^search/$", umap_views.search, name="search"),
    re_path(r"^about/$", umap_views.about, name="about"),
    re_path(r"^user/(?P<username>.+)/$", umap_views.user_maps, name="user_maps"),
)

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + []
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/detail.html
{% extends "media_classification/index.html" %}

{% load i18n common_tags %}

{% block data_app %}classification{% endblock %}
{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Classification project" %}</h2>
        </div>	
        <div class="panel-body">
          <h2>{{ project.name }}</h2>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Research project" %}</h2>
        </div>
        <div class="panel-body">
          <h2>
            <span class="fa fa-flask"></span>
            <a href="{% url 'research:project_detail' pk=project.research_project.pk %}">
              {{ project.research_project.acronym }}
            </a>
          </h2>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Flags" %}</h2>
        </div>
        <div class="panel-body">
          <label class="control-label">{% trans "Sequences" %}:</label>
          <span class="label label-default">{{ project.enable_sequencing }}</span>
          <label class="control-label">{% trans "Status" %}:</label>
          <span class="label label-default">{{ project.get_status_display }}</span>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Actions" %}</h2>
        </div>
        <div class="panel-body">
          {% if project.can_update %}
          <a href="{% url "media_classification:project_update" project.pk %}"
             class="btn btn-default" role="button">
            <span class="fa fa-pencil"></span> {% trans "Update" %}
          </a>
          <a href="{% url "media_classification:classification_import" project.pk %}"
             class="btn btn-default" role="button">
            <span class="fa fa-upload"></span> {% trans "Import results" %}
          </a>
          <a href="{% url "media_classification:classification_export" project.pk %}"
             class="btn btn-default" role="button">
            <span class="fa fa-download"></span> {% trans "Export results" %}
          </a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Project results" %}</h2>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <ul class="list-group list-group-rich">
                {% with project.get_classification_stats as stats %}
                <li class="list-group-item">
                  <span
		    title="Number of resources with user classifications (approved)">
		    {% trans "User classifications" %}:
		  </span>
                  <strong>
		    {{ stats.classified }} ({{ stats.approved }})
		  </strong>
                </li>
                <li class="list-group-item">
                  <span 
                    title="Number of resources with AI classification (approved)">
		    {% trans "AI classifications" %}:
		  </span>
                  <strong>
		    {{ stats.classified_ai }} ({{ stats.approved_ai }})
		  </strong>
                </li>
                <li class="list-group-item">
                  <span 
                    title="Number of resources without classification">
		    {% trans "Unclassified" %}:</span>
                  <strong>
		    {{ stats.unclassified }}
		  </strong>
                </li>
                {% endwith %}
              </ul>
            </div>
	    {% if project.can_view_classifications %}
            <div class="col-md-4">
              <div class="row">
                <div class="col-md-12" style="padding: 2px">
                  <a
		    href="{% url 'media_classification:classification_list' pk=project.pk %}"
                    class="btn btn-success btn-block"
		    style="text-align: left">
                    <i class="fa fa-eye" style="margin-right: 5px"></i> {% trans "Classification results" %}
                  </a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12"  style="padding: 2px">
                  <a
		    href="{% url 'media_classification:ai_classification_list' project_id=project.pk %}"
                    class="btn btn-primary btn-block" style="text-align: left">
                    <i class="fa fa-eye" style="margin-right: 5px"></i> {% trans "AI Classifications" %}
                  </a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12"  style="padding: 2px">
                  <a
		    href="{% url 'media_classification:user_classification_list' pk=project.pk %}"
                    class="btn btn-success btn-block"
		    style="text-align: left">
                    <i class="fa fa-eye" style="margin-right: 5px"></i> {% trans "Users' classifications" %}
                  </a>
                </div>
              </div>
            </div>
	    {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading collapsable">
      <h2 class="panel-title">{% trans "Users in the project" %}</h2>
    </div>
    {% with project.get_user_roles_with_profiles as project_roles %}
    {% if project_roles %}
    <table class="table table-striped table-rich">
      <thead>
        <tr>
          <th></th>
          <th>{% trans "User" %}</th>
          <th>{% trans "Role" %}</th>
          <th>{% trans "E-mail" %}</th>
          <th>{% trans "Institution" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for role in project_roles %}
        {% with role.user.userprofile as user_profile %}
        <tr>
          <td>
            <a href="{% url 'accounts:show_profile' role.user %}">
              <img src="{{ user_profile.avatar_url }}" alt="{{ role.user.username }}"
                   class="img-thumbnail avatar-small" style="display:inline">
            </a>
          </td>
          <td>
            <a href="{% url 'accounts:show_profile' role.user %}">
	      {{ role.user|pretty_username }}
	    </a>
          </td>
          <td>{{ role.get_name_display }}</td>
          <td>
	    <a href="mailto:{{ role.user.email }}">
	      {{ role.user.email|default:"" }}
	    </a>
	  </td>
          <td>{{ user_profile.institution|default:"" }}</td>
          {% endwith %}
          {% endfor %}
      </tbody>
    </table>
    {% endif %}
    {% endwith %}
  </div>
</div>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">{% trans "Classificator" %}</h2>
    </div>
    <div class="panel-body">
      {% if project.classificator %}
      <a href="{% url 'media_classification:classificator_detail' pk=project.classificator.pk %}">{{ project.classificator.name }}</a>
      {% else %}
      There is no classificator assigned to this project.
      {% endif %}
    </div>
  </div>
</div>

<h2 class="container">{% trans "Collections" %}</h2>
{% with grid_context=collection_context %}
{% include 'media_classification/projects/detail_collection_grid.html' %}
{% endwith %}

{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/detail_collection_grid.html
{% extends "common/grid.html" %}

{% load i18n %}

{% block filters %}

<div class="form-group form-filter">
  <label for="status" class="control-label">{% trans "Status" %}</label>
  <select
     id="status"
     class="form-control"
     filter-text="status"
     filter-service="filter"
     ng-model="filters.status"
     ng-options="option.value as option.label for option in optionList.status">
  </select>
</div>

<div class="form-group form-filter">
  <label for="status" class="control-label">{% trans "Active" %}</label>
  <select
     id="is_active"
     class="form-control"
     filter-text="is_active"
     filter-service="filter"
     ng-model="filters.is_active"
     ng-options="option.value as option.label for option in optionList.bool">
  </select>
</div>
{% endblock %}

{% block custom_actions %}

{% if not grid_context.hide_show_on_map %}
{% url 'geomap:map_view' as new_map_url %}
<action-show-map data-type="collections" data-url="{{ new_map_url }}"
                 data-field="collection_pk">
  <select>
    <option value="{{ new_map_url }}" selected>{% trans "New map" %}</option>
    {% for map in grid_context.maps %}
    <option value="{% url 'geomap:map' slug=map.slug pk=map.pk %}">{{ map }}</option>
    {% endfor %}
  </select>
</action-show-map>
{% endif %}

{% if user.is_authenticated and project.can_update %}
<action-build-sequences ng-disabled="!data.selectedCounter" ng-click="execute('{% url "media_classification:sequence_build" %}')">
</action-build-sequences>
<action-import-attrs ng-disabled="!data.selectedCounter" ng-click="execute('{% url "media_classification:classification_importattrs" pk=object.pk %}')">
</action-import-attrs>

{% endif %}

{% endblock%}

{% block custom_actions_list %}

{% if user.is_authenticated and project.can_update %}
    <li>
      <action-unlink2-selected ng-click="execute($event, '{% url "media_classification:project_collection_delete_multiple" %}')">
      </action-unlink2-selected>
    </li>
    <li>
      <action-blur-humans ng-click="execute($event, '{% url "media_classification:project_collection_blur_humans" %}')">
      </action-blur-humans>
    </li>
{% endif %}

{% endblock %}

{% block table_cells %}

<td data-title="'Name'" sortable="'name'">{[{ record.name }]}</td>
<td data-title="'Status'" sortable="'status'">{[{ record.status }]}</td>
<td data-title="'Is active'" sortable="'is_active'">{[{ record.is_active }]}</td>
<td data-title="'Total'">{[{ record.total_count }]}</td>
<td data-title="'Classified'">{[{ record.classified_count }]}</td>
<td data-title="'Approved'">{[{ record.approved_count }]}</td>

{% endblock %}

{% block table_cells_extra_actions %}
</td>
<td>
  <action-classify-collection 
     ng-if="record.classify_data"
     ng-click="execute($event, record)">
  </action-classify-collection>

  {% if project.deployment_based_nav %}
  <input
     type="text"
     placeholder="Select deployment (optionally)"
     class="select2ajax"
     style="width:260px"
     multiple="true"
     id="deployment"
     ng-model="filters.deployments[record.pk]"
     ng-if="record.classify_data"
     filter-tokens="deployments"
     filter-api-url='{% url "geomap:api-deployment-list" %}?classification_project={{ project.pk }}'
     filter-text-label="deployment_id"
     filter-id-label="pk"
     filter-multiple="true"
     filter-service="filter">
  </input>
{% endif %}
</td>
{% endblock %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/form_inline.html
{% load i18n %}

<div class="form-inline">

    <div class="checkbox-inline">
        <label>
            {{ form.deployment_based_nav }}
            {% trans "Deployment-based navigation" %}
        </label>
    </div>

    <div class="checkbox-inline">
        <label>
            {{ form.enable_sequencing }}
            {% trans "Sequences" %}
        </label>
    </div>

    <div class="checkbox-inline">
        <label>
            {{ form.enable_crowdsourcing }}
            {% trans "Crowdsourcing" %}
        </label>
    </div>

</div>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/list.html
{% extends "media_classification/index.html" %}

{% load common_tags %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
    {% with grid_context=classification_project_context %}
    {% include 'media_classification/projects/grid.html' %}
    {% endwith %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/sequence_build_form.html
{% load i18n crispy_forms_tags %}

<form action="." method="post" class="panel-body">
    {% crispy form form.helper %}
    <fieldset>
        <button type="submit" class="btn btn-primary">{% trans "(Re)build sequences" %}</button>
    </fieldset>
</form>