trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import include
from django.urls import reverse_lazy, path, re_path
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

import trapper.apps.media_classification.views.ai_classifications
from trapper.apps.media_classification.views import (
    api as classification_api_views,
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    ai_classifications as ai_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views,
)

app_name = "media_classification"

router = DefaultRouter(trailing_slash=False)

router.register(
    r"classificators",
    classification_api_views.ClassificatorViewSet,
    basename="api-classificator",
)

router.register(
    r"user-classifications",
    classification_api_views.UserClassificationViewSet,
    basename="api-user-classification",
)

router.register(
    r"classifications",
    classification_api_views.ClassificationViewSet,
    basename="api-classification",
)

router.register(
    r"ai-classifications",
    classification_api_views.AIClassificationViewSet,
    basename="api-ai-classification",
)

router.register(
    r"classifications_map",
    classification_api_views.ClassificationMapViewSet,
    basename="api-classification-map",
)

router.register(
    r"projects",
    classification_api_views.ClassificationProjectViewSet,
    basename="api-classification-project",
)

router.register(
    r"project/(?P<project_pk>\d+)/collections",
    classification_api_views.ClassificationProjectCollectionViewSet,
    basename="api-classification-project-collection",
)

router.register(
    r"sequences", classification_api_views.SequenceViewSet, basename="api-sequence"
)

router.register(
    r"collection/(?P<collection_pk>\d+)/resources/$",
    classification_api_views.ClassificationResourcesViewSet,
    basename="api-classification-resources",
)

urlpatterns = [
    re_path(r"^api/", include(router.urls)),
    re_path(
        r"^api/classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsView.as_view(),
        name="api-classification-results",
    ),
    re_path(
        r"^api/ai-classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.AIClassificationResultsView.as_view(),
        name="api-ai-classification-results",
    ),
    re_path(
        r"^api/classifications/results/agg/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsAggView.as_view(),
        name="api-classification-results-agg",
    ),
    re_path(
        r"^api/classifications/import/",
        classification_api_views.ClassificationImport.as_view(),
        name="api-classification-import",
    ),
    re_path(
        r"^api/media/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationProjectMediaTableView.as_view(),
        name="api-media-export",
    ),
    re_path(
        r"^api/package/(?P<project_pk>\d+)/",
        classification_api_views.ResultsDataPackageAPIView.as_view(),
        name="api-package-export",
    ),
    path(
        "api/classify/ai/callback/<str:ai_provider_token>/",
        classification_api_views.classify_ai_callback,
        name="api-classify-ai-callback",
    ),
    path(
        "api/classify/ai/classification_extra/<str:ai_provider_token>/<str:classification_job_id>/<str:resource_name>/",
        classification_api_views.classify_ai_extra_resource,
        name="api-classify-ai-extra",
    ),
]

urlpatterns += [
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("media_classification:project_list")),
        name="project_index",
    ),
    # Project views
    re_path(r"project/list/$", projects_views.view_project_list, name="project_list"),
    re_path(
        r"project/detail/(?P<pk>\d+)/$",
        projects_views.view_project_detail,
        name="project_detail",
    ),
    re_path(
        r"project/create/$", projects_views.view_project_create, name="project_create"
    ),
    re_path(
        r"project/update/(?P<pk>\d+)/$",
        projects_views.view_project_update,
        name="project_update",
    ),
    re_path(
        r"project/delete/(?P<pk>\d+)/$",
        projects_views.view_project_delete,
        name="project_delete",
    ),
    re_path(
        r"^project/delete/$",
        projects_views.view_project_delete,
        name="project_delete_multiple",
    ),
    re_path(
        r"project/collection/add/$",
        projects_views.view_project_collection_add,
        name="project_collection_add",
    ),
    re_path(
        r"project/collection/delete/(?P<pk>\d+)/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete",
    ),
    re_path(
        r"^project/collection/delete/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete_multiple",
    ),
    re_path(
        r"^project/collection/blur/$",
        projects_views.view_project_collection_blur_humans,
        name="project_collection_blur_humans",
    ),
    # Classificator views
    re_path(
        r"classificator/list/$",
        classificators_views.view_classificator_list,
        name="classificator_list",
    ),
    re_path(
        r"classificator/detail/(?P<pk>\d+)/$",
        classificators_views.view_classificator_detail,
        name="classificator_detail",
    ),
    re_path(
        r"classificator/create/$",
        classificators_views.view_classificator_create,
        name="classificator_create",
    ),
    re_path(
        r"classificator/update/(?P<pk>\d+)/$",
        classificators_views.view_classificator_update,
        name="classificator_update",
    ),
    re_path(
        r"classificator/clone/(?P<pk>\d+)/$",
        classificators_views.view_classificator_clone,
        name="classificator_clone",
    ),
    re_path(
        r"^classificator/delete/(?P<pk>\d+)/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete",
    ),
    re_path(
        r"^classificator/delete/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete_multiple",
    ),
    # Sequence views
    re_path(
        r"sequence/create/$",
        sequences_views.view_sequence_change,
        name="sequence_create",
    ),
    re_path(
        r"sequence/update/$",
        sequences_views.view_sequence_change,
        name="sequence_update",
    ),
    re_path(
        r"sequence/change/$",
        sequences_views.view_sequence_change,
        name="sequence_change",
    ),
    re_path(
        r"sequence/delete/$",
        sequences_views.view_sequence_delete,
        name="sequence_delete",
    ),
    re_path(
        r"^sequence/build/$", sequences_views.view_sequence_build, name="sequence_build"
    ),
    # Classification views
    re_path(
        r"^classification/overview/$",
        classifications_views.view_classification_overview,
        name="classification_overview",
    ),
    re_path(
        r"^classification/list/(?P<pk>\d+)/$",
        classifications_views.view_classification_list,
        name="classification_list",
    ),
    re_path(
        r"classification/import/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/import/(?P<pk>\d+)/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/export/(?P<pk>\d+)/$",
        classifications_views.view_classification_export,
        name="classification_export",
    ),
    re_path(
        r"classification/publish/$",
        classifications_views.view_classification_publish,
        name="classification_publish",
    ),
    re_path(
        r"classification/feedback/(?P<pk>\d+)/$",
        classifications_views.view_classification_feedback,
        name="classification_feedback",
    ),
    re_path(
        r"classification/export-agg/(?P<pk>\d+)/$",
        classifications_views.view_classification_export_agg,
        name="classification_export_agg",
    ),
    re_path(
        r"classification/importattrs/(?P<pk>\d+)/$",
        classifications_views.view_classification_import_attrs,
        name="classification_importattrs",
    ),
    re_path(
        r"^classification/delete/(?P<pk>\d+)/$",
        classifications_views.view_classification_delete,
        name="classification_delete",
    ),
    re_path(
        r"^classification/delete/$",
        classifications_views.view_classification_delete,
        name="classification_delete_multiple",
    ),
    re_path(
        r"^classification/bulk-update/$",
        classifications_views.view_classification_bulk_update,
        name="classification_bulk_update",
    ),
    re_path(
        r"classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$",
        classifications_views.view_classify_collection,
        name="classify_collection",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify_user",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    path(
        "classify/<int:pk>/ai/<int:ai_provider_id>/",

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy, re_path
from django.views.decorators.cache import cache_control, cache_page, never_cache
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from trapper.apps.accounts.views import accounts as accounts_views
from umap import views as umap_views
from umap.decorators import (
    map_permissions_check,
    login_required_if_not_anonymous_allowed,
)
from umap.utils import decorated_patterns

admin.autodiscover()


swagger_schema_view = get_schema_view(
    openapi.Info(
        title="TRAPPER API",
        default_version="v1",
        description="",
        terms_of_service="terms of service",
        contact=openapi.Contact(email="contact@os-conservation.org"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=[permissions.IsAuthenticated],
)


urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    re_path(
        r"^account/inactive/$",
        RedirectView.as_view(url=reverse_lazy("trapper_index")),
        name="account_inactive",
    ),
    # Trapper homepage
    re_path(r"^$", accounts_views.view_index, name="trapper_index"),
    # Media classification urls
    re_path(
        r"^media_classification/",
        include("trapper.apps.media_classification.urls", "media_classification"),
    ),
    # Research urls
    re_path(r"^research/", include("trapper.apps.research.urls")),
    # Storage urls
    re_path(r"^storage/", include("trapper.apps.storage.urls", "storage")),
    # Messaging urls
    re_path(r"^messaging/", include("trapper.apps.messaging.urls")),
    # Accounts urls
    re_path("", include("django.contrib.auth.urls")),
    re_path(r"^accounts/", include("trapper.apps.accounts.urls")),
    re_path(r"^account/", include("allauth.urls")),
    # GeoMap urls
    re_path(r"^geomap/", include("trapper.apps.geomap.urls")),
    # Comments
    re_path(r"^comments/", include("trapper.apps.comments.urls")),
    # Extra tables
    re_path(r"^tables/", include("trapper.apps.extra_tables.urls")),
    # Sendfile urls
    re_path(r"^serve/", include("trapper.apps.sendfile.urls")),
    re_path(r"^grappelli/", include("grappelli.urls")),
    re_path(r"^admin/", admin.site.urls),
    # REST API Swagger docs
    re_path(
        r"^docs/api/swagger(?P<format>\.json|\.yaml)$",
        swagger_schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^docs/api/$",
        swagger_schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^docs/api/redoc/$",
        swagger_schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # Debug Toolbar
    re_path(r"^__debug__/", include(debug_toolbar.urls)),
    # JupyterLite urls
    re_path(r"^jupyterlite/", include("trapper.apps.jupyterlite.urls")),
]

# Umap patterns
urlpatterns += (
    re_path(
        r"^map/(?P<pk>\d+)/geojson/$",
        umap_views.MapViewGeoJSON.as_view(),
        name="map_geojson",
    ),
    re_path(
        r"^map/anonymous-edit/(?P<signature>.+)$",
        umap_views.MapAnonymousEditUrl.as_view(),
        name="map_anonymous_edit_url",
    ),
    re_path(
        r"^pictogram/json/$",
        umap_views.PictogramJSONList.as_view(),
        name="pictogram_list_json",
    ),
    re_path(
        r"^$",
        accounts_views.view_index,
        name="user_dashboard",
    ),
)
urlpatterns += decorated_patterns(
    cache_control(must_revalidate=True),
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/$",
        umap_views.DataLayerView.as_view(),
        name="datalayer_view",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/versions/$",
        umap_views.DataLayerVersions.as_view(),
        name="datalayer_versions",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/(?P<name>[_\w]+.geojson)$",
        umap_views.DataLayerVersion.as_view(),
        name="datalayer_version",
    ),  # noqa
)
urlpatterns += decorated_patterns(
    [ensure_csrf_cookie],
    re_path(
        r"^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$", umap_views.MapView.as_view(), name="map"
    ),  # noqa
    re_path(r"^map/new/$", umap_views.MapNew.as_view(), name="map_new"),
)
urlpatterns += decorated_patterns(
    [login_required_if_not_anonymous_allowed, never_cache],
    re_path(r"^map/create/$", umap_views.MapCreate.as_view(), name="map_create"),
)
urlpatterns += decorated_patterns(
    [map_permissions_check, never_cache],
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/settings/$",
        umap_views.MapUpdate.as_view(),
        name="map_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/permissions/$",
        umap_views.UpdateMapPermissions.as_view(),
        name="map_update_permissions",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/owner/$",
        umap_views.AttachAnonymousMap.as_view(),
        name="map_attach_owner",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/delete/$",
        umap_views.MapDelete.as_view(),
        name="map_delete",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/clone/$",
        umap_views.MapClone.as_view(),
        name="map_clone",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/create/$",
        umap_views.DataLayerCreate.as_view(),
        name="datalayer_create",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$",
        umap_views.DataLayerUpdate.as_view(),
        name="datalayer_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$",
        umap_views.DataLayerDelete.as_view(),
        name="datalayer_delete",
    ),
)
urlpatterns += i18n_patterns(
    re_path(
        r"^showcase/$",
        cache_page(24 * 60 * 60)(umap_views.showcase),
        name="maps_showcase",
    ),
    re_path(r"^search/$", umap_views.search, name="search"),
    re_path(r"^about/$", umap_views.about, name="about"),
    re_path(r"^user/(?P<username>.+)/$", umap_views.user_maps, name="user_maps"),
)

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + []
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/ai_classifications/list/breadcrumbs.html
{% load i18n %}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <span class="fa fa-flask"></span> <a
                        href="{% url 'research:project_detail' pk=grid_context.project.research_project.pk %}">{{ grid_context.project.research_project.acronym }}</a>
                    >
                    <span class="fa fa-cubes"></span> <a
                        href="{% url 'media_classification:project_detail' pk=grid_context.project.pk %}">{{ grid_context.project.name }}</a>
                    > <strong>{% trans "AI classifications" %}</strong>
                </h2>
            </div>
        </div>
    </div>
</div>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/ai_classifications/list/filters.html
{% load i18n %}

{#- Confidence -> albo lista co 0.05 albo liczba do wpisania; zakres 0-1#}

<div class="form-group form-filter">
    <label for="type" class="control-label">{% trans "File type" %}</label>
    <select
            id="type"
            class="form-control"
            filter-text="ftype"
            filter-service="filter"
            ng-model="filters.ftype"
            ng-options="option.value as option.label for option in optionList.media">
    </select>
</div>

<div class="form-group form-filter">
    <label for="approved" class="control-label">{% trans "Approved" %}</label>
    <select
            id="approved"
            class="form-control"
            filter-text="approved"
            filter-service="filter"
            ng-model="filters.approved"
            ng-options="option.value as option.label for option in optionList.bool">
    </select>
</div>

<div class="form-group form-filter">
    <label for="bboxes" class="control-label">{% trans "Bboxes" %}</label>
    <select
            id="bboxes"
            class="form-control"
            filter-text="bboxes"
            filter-service="filter"
            ng-model="filters.bboxes"
            ng-options="option.value as option.label for option in optionList.bool">
    </select>
</div>

{% for definition in grid_context.filters %}
    {% if definition.tag %}
        <div class="form-group form-filter">
            <label for="{{ definition.name }}" class="control-label" title="{{ definition.label }}">
                {% trans definition.label|truncatechars:12 %}
            </label>
            <{{ definition.tag.name }}
            id="{{ definition.name }}"
            class="form-control"
            filter-text="{{ definition.name }}"
            filter-service="filter"
            ng-model="filters['{{ definition.name }}']"
            {% if definition.values %}
                ng-options="option.value as option.label for option in [{% for val, label in definition.values %}
                {'label': '{{ label }}', 'value': '{{ val }}'}{% if not forloop.lat %},{% endif %}{% endfor %}]"
            {% endif %}
            {% if definition.tag.is_block %}>
                </{{ definition.tag.name }}>
            {% else %}
                />
            {% endif %}
        </div>
    {% endif %}
{% endfor %}

<div class="form-group form-filter-full">
    <label for="collections" class="control-label">{% trans "AI Providers" %}</label>
    <select
            type="text"
            id="ai_providers"
            class="select2-default"
            multiple
            ng-model="filters.ai_provider"
            filter-tokens="ai_provider.name"
            filter-service="filter">
        {% for ai_provider in grid_context.ai_providers %}
            <option value="{{ ai_provider.0 }}">{{ ai_provider.1 }}</option>
        {% endfor %}
    </select>
</div>

<div class="form-group form-filter-full">
    <label for="collections" class="control-label">{% trans "Collections" %}</label>
    <select
            type="text"
            id="collection"
            class="select2-default"
            multiple
            ng-model="filters.collection"
            filter-tokens="collection.name"
            filter-service="filter">
        {% for collection in grid_context.collections %}
            <option value="{{ collection.0 }}">{{ collection.1 }}</option>
        {% endfor %}
    </select>
</div>

<div class="form-group form-filter-full">
    <label for="deployments" class="control-label">{% trans "Deployments" %}</label>
    <input
            type="text"
            class="select2ajax"
            multiple="true"
            id="deployment"
            ng-model="filters.deployment"
            filter-tokens="deployment"
            filter-api-url='{% url "geomap:api-deployment-list" %}?classification_project={{ grid_context.project.pk }}'
            filter-text-label="deployment_id"
            filter-id-label="pk"
            filter-multiple="true"
            filter-service="filter">
</div>

<div class="form-group form-filter-full">
    <label for="species" class="control-label">{% trans "Species" %}</label>
    <input
            type="text"
            class="select2ajax"
            multiple="true"
            id="species"
            ng-model="filters.species"
            filter-tokens="species"
            filter-api-url='{% url "extra_tables:api-species-list" %}'
            filter-text-label="__str__"
            filter-id-label="pk"
            filter-multiple="true"
            filter-service="filter">
</div>

<div class="form-group form-filter-full">
    <label for="confidence" class="control-label">{% trans "Confidence" %}</label>
    <input
            id="confidence"
            class="form-control"
            min="0"
            max="1"
            step="0.01"
            type="number"
            ng-model="filters.confidence"
            filter-text="confidence"
            filter-service="filter"
    >
</div>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/ai_classifications/list/grid.html
{% extends "common/grid.html" %}

{% load i18n %}

{% block breadcrumbs %}
    {% include "./breadcrumbs.html" %}
{% endblock %}

{% block filters %}

    {% include "./filters.html" %}

{% endblock %}

{% block my_objects %}
    {% if user.is_authenticated %}
        <button
                type="button"
                class="btn btn-default"
                ng-class="{ active: filters.owner }"
                ng-model="filters.owner"
                ng-init="filters.owner = false"
                ng-click="filterOwner()"
                filter-checkbox="{ name: 'owner', value: '{{ user.pk }}' }"
                filter-service="filter">{% trans "My classifications" %}</button>
    {% endif %}
{% endblock %}

{% block custom_actions %}
{% if grid_context.is_admin %}
<action-export-with-filters ng-click="execute('{% url "media_classification:api-ai-classification-results" project_pk=grid_context.project.pk %}')">
</action-export-with-filters>
{% endif %}
{% endblock%}
	
{% block custom_actions_list %}
    {% if grid_context.is_admin %}
        <li>
            <action-classify-ai
                    ng-click="execute($event, '{% url "media_classification:classify_ai" pk=grid_context.project.pk obj="aiclassification" %}')">
            </action-classify-ai>
        </li>
        <li>
            <action-approve-selected-ai-classifications
                    ng-click="execute($event, '{% url "media_classification:ai_classification_bulk_approve" project_id=grid_context.project.pk %}')">
            </action-approve-selected-ai-classifications>
        </li>
        <li>
            <action-remove-selected
                    ng-click="execute($event, '{% url "media_classification:ai_classification_delete_multiple" %}')">
            </action-remove-selected>
        </li>
        <li>
            <action-copy-bboxes-from-ai
                    ng-click="execute($event, '{% url "media_classification:ai_classification_copy_bboxes" project_id=grid_context.project.pk %}')">
            </action-copy-bboxes-from-ai>
        </li>
    {% endif %}
{% endblock %}

{% block table_cells %}
    {% include "./list_item.html" %}
{% endblock %}

{% block table_cells_extra_actions %}
{#    <action-user-classification-details#}
{#            ng-click="execute($event, record, {{ grid_context.project.deployment_based_nav|yesno:'true,false' }})">#}
{#    </action-user-classification-details>#}
{% endblock %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/ai_classifications/list/list.html
{% extends "media_classification/index.html" %}

{% load common_tags %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
    {% with grid_context=ai_classification_context %}
    {% include './grid.html' %}
    {% endwith %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/ai_classifications/list/list_item.html
{% load i18n %}

<td data-title="'Thumbnail'">
    <div
            ng-if="record.resource.resource_type == 'I'"
            data-src="{[{ record.resource.url }]}"
            class="img-thumbnail"
            ng-click="openGallery($event)"
            title="{[{ record.resource.name }]}">
        <img ng-src="{[{ record.resource.thumbnail_url }]}"/>
    </div>
    <div ng-if="record.resource.resource_type == 'V'" style="display:none;" id="video{[{ $index }]}">
        <video class="lg-video-object lg-html5 video-js" controls preload="none">
            <source src="{[{ record.resource.url }]}#t=0.1" type="{[{ record.resource.mime }]}">
        </video>
    </div>
    <div
            ng-if="record.resource.resource_type == 'V'"
            data-html="#video{[{ $index }]}"
            class="img-thumbnail"
            ng-click="openGallery($event)"
            title="{[{ record.resource.name }]}">
        <img ng-src="{[{ record.resource.thumbnail_url }]}"/>
    </div>
</td>
<td data-title="'Type'" sortable="'resource.resource_type'"
    ng-bind-html="record.resource.resource_type | typesIcon"></td>
<td data-title="'Name'" sortable="'resource.name'">{[{ record.resource.name }]}</td>
<td data-title="'Date recorded'">{[{ record.resource.date_recorded | dateTZ: dateFormat.table }]}</td>
{#<td data-title="'User'" sortable="'owner'"><a ng-href="{[{ record.owner_profile }]}">{[{ record.owner }]}</a></td>#}
<td data-title="'AI Provider'" sortable="'ai_provider'">{[{ record.ai_provider }]}</td>
{#<td data-title="'Updated'">{[{ record.updated_at | dateTZ: dateFormat.table }]}</td>#}
<td data-title="'Approved'" ng-bind-html="record.approved | classifiedAIIcons"></td>
<td data-title="'Attributes'">
    <h6>{% trans "Static attributes" %}:</h6>
    <div class="tags-list">
    <span
            ng-repeat="(label, tag) in record.static_attrs"
            ng-if="label != 'comments' && label != 'annotations'"
            class="label label-success">{[{ label }]}: {[{ tag }]}
    </span>
    </div>
    <h6>{% trans "Dynamic attributes" %}:</h6>
    <div class="tags-list" ng-repeat="dynamic_attr in record.dynamic_attrs" ng-init="tagIndex = $index">
    <span
            ng-repeat="(label, tag) in dynamic_attr"
            class="label" title="{[{ tag }]}"
            ng-class="{'label-default': tagIndex % 2 == 0, 'label-success': tagIndex % 2 != 0}">{[{ label }]}: {[{ tag
        }]}</span>
    </div>
</td>